#!/bin/bash -e
#
# Copyright (c) 2017, Richard Mortier <mort@cantab.net>
# @license LICENSE.txt
#
# Scrape all Open Banking open API endpoints

if [ "$#" -ne 1 ]; then
  echo "usage: $(basename "$0") COMMIT-MSG"
  exit 1
fi
COMMITMSG=$1

# silent, with errors, insecure (Bank of Ireland TLS cert...), decompress if
# compressed data returned
CURL="curl -sSk --compressed"

PLATFORM=$(uname -s)

BASEURL=https://developer.openbanking.org.uk/open-data/participant-store
CATALOG=participant_store.json
ENDPOINTS=name-endpoints.json

case $PLATFORM in
  Darwin )
    JQ="docker run -i --rm -v "$(pwd -P)":/cwd -w /cwd mor1/jq:latest"
    ;;
  Linux )
    JQ="/home/rmm1002/openbanking-scripts/jq-linux64"
    ;;
  * )
    echo "ERR: unknown PLATFORM=$PLATFORM"
    exit 1
    ;;
esac

# fetch the endpoint catalogue
pushd $(dirname $0)/data >/dev/null
$CURL -O $BASEURL/$CATALOG

# process catalogue to extract all (name,endpoint) pairs
$JQ '.data[] as $d '`
    `'| { mtime: .meta.LastUpdated,'`
        `'name: $d.name,'`
        `'urls: ['`
        `'  $d.baseUrl'`
        `'  + "/" + ($d.supportedAPIs | to_entries | .[] | .value[]'`
        `'  + "/" + .key)'`
        `']}' \
          $CATALOG >| $ENDPOINTS

# iterate over (name,endpoint) pairs to fetch data
$JQ '(.name | gsub("[^A-Za-z0-9._-]";"";"g")) + " " + (.urls[])' $ENDPOINTS \
  | tr -d '"' \
  | while read name url;
do
  $CURL $url | $JQ '.' >| "$name-$(basename $url).json"
done

# commit any modifications to the datastore
git add .
git commit -am "$COMMITMSG" >/dev/null

# done
popd >/dev/null
